// T06-React/02-staging/05_src_github搜索案例_axios/components/List/index.jsx
import React, { Component } from 'react'
import './index.css'

export default class List extends Component {
  render() {
    const { users, isFirst, isLoading, err } = this.props
    return (
      <div className="row">
        {isFirst ? (
          <h2>欢迎使用，输入关键字，随后点击搜索</h2>
        ) : isLoading ? (
          <h2>Loading......</h2>
        ) : err ? (
          <h2 style={{ color: 'red' }}>{err}</h2>
        ) : (
          users.map((userObj) => {
            return (
              <div key={userObj.id} className="card">
                <a rel="noreferrer" href={userObj.html_url} target="_blank">
                  <img alt="head_portrait" src={userObj.avatar_url} style={{ width: '100px' }} />
                </a>
                <p className="card-text">{userObj.login}</p>
              </div>
            )
          })
        )}
      </div>
    )
  }
}

// T05-Vue/Vue2/03-脚手架项目/14_src_搜索gitHub/components/List.vue
<template>
	<div class="row">
		<!-- 展示用户列表 -->
		<div v-show="info.users.length" class="card" v-for="user in info.users" :key="user.login">
			<a :href="user.html_url" target="_blank">
				<img :src="user.avatar_url" style='width: 100px' />
			</a>
			<p class="card-text">{{ user.login }}</p>
		</div>
		<!-- 展示欢迎词 -->
		<h1 v-show="info.isFirst">欢迎使用！</h1>
		<!-- 展示加载中 -->
		<h1 v-show="info.isLoading">加载中....</h1>
		<!-- 展示错误信息 -->
		<h1 v-show="info.errMsg">{{ info.errMsg }}</h1>
	</div>
</template>

<script>
export default {
	name: 'List',
	data() {
		return {
			info: {
				isFirst: true,
				isLoading: false,
				errMsg: '',
				users: []
			}
		};
	},
	mounted() {
		this.$bus.$on('updateListData', (dataObj) => {
			this.info = dataObj;
		});
	},
};
</script>

<style scoped>
.album {
	min-height: 50rem;
	padding-top: 3rem;
	padding-bottom: 3rem;
	background-color: #f7f7f7;
}

.card {
	float: left;
	width: 33.333%;
	padding: .75rem;
	margin-bottom: 2rem;
	border: 1px solid #efefef;
	text-align: center;
}

.card>img {
	margin-bottom: .75rem;
	border-radius: 100px;
}

.card-text {
	font-size: 85%;
}
</style>
