// T06-React/02-staging/05_src_github搜索案例_axios/components/Search/index.jsx
import React, { Component } from 'react'
import axios from 'axios'

export default class Search extends Component {
  search = () => {
    //获取用户的输入(连续解构赋值+重命名)
    const {
      keyWordElement: { value: keyWord }
    } = this
    //发送请求前通知App更新状态
    this.props.updateAppState({ isFirst: false, isLoading: true })
    //发送网络请求
    axios.get(`/api1/search/users?q=${keyWord}`).then(
      (response) => {
        //请求成功后通知App更新状态
        this.props.updateAppState({ isLoading: false, users: response.data.items })
      },
      (error) => {
        //请求失败后通知App更新状态
        this.props.updateAppState({ isLoading: false, err: error.message })
      }
    )
  }

  render() {
    return (
      <section className="jumbotron">
        <h3 className="jumbotron-heading">搜索github用户</h3>
        <div>
          <input ref={(c) => (this.keyWordElement = c)} type="text" placeholder="输入关键词点击搜索" />
          &nbsp;
          <button onClick={this.search}>搜索</button>
        </div>
      </section>
    )
  }
}

// T05-Vue/Vue2/03-脚手架项目/14_src_搜索gitHub/components/Search.vue
<template>
	<section class="jumbotron">
		<h3 class="jumbotron-heading">Search Github Users</h3>
		<div>
			<input type="text" placeholder="enter the name you search" v-model="keyWord" />&nbsp;
			<button @click="searchUsers">Search</button>
		</div>
	</section>
</template>

<script>
import axios from 'axios';
export default {
	name: 'Search',
	data() {
		return {
			keyWord: ''
		};
	},
	methods: {
		searchUsers() {
			// 请求成功就渲染列表, 失败就清空列表
			axios.get(`https://api.github.com/search/users?q=${this.keyWord}`)
				.then(response => this.$bus.$emit('updateListData', { isLoading: false, errMsg: '', users: response.data.items, isFirst: false }))
				.catch(error => this.$bus.$emit('updateListData', { isLoading: false, errMsg: error.message, users: [], isFirst: false }));
		}
	},
};
</script>
